plugins {
    id 'java'
    id 'maven-publish'
    id 'com.diffplug.spotless' version "8.1.0"
}

group = 'fr.minuskube.inv'
version = '1.2.7-OCC'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }

    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
    maven { url = uri("https://repo.pgm.fyi/snapshots") }
    maven { url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/") }
    maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots") }
}

dependencies {
    compileOnly 'app.ashcon:sportpaper:1.8.8-R0.1-SNAPSHOT'
}

spotless {
    java {
        target 'src/**/*.java'
        googleJavaFormat()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

tasks.named('build') {
    dependsOn 'spotlessApply'
}

tasks.withType(Javadoc).configureEach {
    options.links(
        "https://hub.spigotmc.org/javadocs/spigot/",
        "https://docs.oracle.com/javase/8/docs/api/"
    )
    options.addStringOption("Xdoclint:none", "-quiet")
}

tasks.jar {
    archiveFileName.set("SmartInvs-${project.version}.jar")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom {
                name.set("SmartInvs")
                description.set("Advanced Inventory API for your Minecraft Bukkit plugins (Overcast Community Fork")
                url.set("https://github.com/applenick/SmartInvs")

                licenses {
                    license {
                        name.set("GNU General Public License v3.0")
                        url.set("https://www.gnu.org/licenses/gpl-3.0.html")
                    }
                }

                developers {
                    developer {
                        id.set("minuskube")
                        name.set("MinusKube")
                        email.set("minuskube@gmail.com")
                    }
                }

                scm {
                    connection.set("scm:git:git://github.com/applenick/SmartInvs.git")
                    developerConnection.set("scm:git:ssh://github.com:applenick/SmartInvs.git")
                    url.set("https://github.com/applenick/SmartInvs")
                }
            }
        }
    }

    repositories {
        maven {
            name = "pgmRepoSnapshots"
            url = uri("https://repo.pgm.fyi/snapshots")

            credentials {
                username = System.getenv("PGM_REPO_USERNAME") ?: "admin"
                password = System.getenv("PGM_REPO_PASS") ?: "password"
            }
        }
    }
}
